DROP PROCEDURE IF EXISTS prc_export;
CREATE PROCEDURE
  prc_export(VARCHAR, VARCHAR, CHAR) AS
$$
BEGIN
  EXECUTE FORMAT('COPY %s TO %L DELIMITER %L CSV;', $1, $2, $3);
END;
$$ LANGUAGE plpgsql;
