DROP PROCEDURE IF EXISTS prc_import;
CREATE PROCEDURE
  prc_import(VARCHAR, VARCHAR, CHAR) AS
$$
BEGIN
  EXECUTE FORMAT('COPY %s FROM %L DELIMITER %L CSV;', $1, $2, $3);
END;
$$ LANGUAGE plpgsql;
